spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    topic: order-topic
    producer:
      bootstrap-servers: localhost:9092
      producer:
        value-serializer: org.springframework.kafka.support.serializer.StringSerializer
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments